### PR TITLE
Command GUI 

### PR DESCRIPTION
**Pull request by scaredycode**
A graphical user interface for easy entry of note sequences and commands.
Can be tested by launching `test_behavior.launch`

Functionality:
- [x] Read notes from camera
- [x] Load song from song library (currently Frère Jacques, All my ducklings, and a basic scale from c' to c'' and back)
- [x] Option to type in a custom lilypond sequence 
- [x] Command Constructor, that only allows valid combinations of "behavior", "action", and "parameter"

scrapped for now:
- [ ] fix camera feed
- [ ] (possibly) include lilypond visualization
- [ ] include audio feedback

### CODE REVIEW

**Comment by Juphex** [comment]
Whats the status? considering not merging anything after the 12.10.

**Review by Juphex — APPROVED** [review]
GUI works for me.
One thing: When you add a number in the "by ... bpm" field the number gets removed when sending "GO". Did you intend it?

**Comment by scaredycode** [comment]
> GUI works for me. One thing: When you add a number in the "by ... bpm" field the number gets removed when sending "GO". Did you intend it?

Hi, yes this is intentional. It is meant to prevent sending the same command twice (or multiple times) without waiting for a result first.

**Comment by scaredycode** [comment]
> Whats the status? considering not merging anything after the 12.10.

For now, I will just remove the Camera Feed placeholder and scrap the other TODOs in order to merge a functional version.
If I get the camera feed to work until Thursday, I will make a new PR, otherwise I leave it our completely.

**Review by Juphex — APPROVED** [review]

**Pull request merged**
