### PR TITLE
Mallet Planning

### LINKED ISSUE #69: Utilize mallet model
Plan using the tip of the modeled mallet

### PR DESCRIPTION
**Pull request by berkgungor**
Closes #69 

Also fixes a few minor related issues:
    - Mallet self collision
    - IK robot state initialization 
    - Change launch file names as they where a bit arbitrary
    - Use header files
    - `kinematics.yaml` for the `arm_mallet` move group

PR by @Flova

### CODE REVIEW

**Comment by Flova** [comment]
No, this code is still wip and untested

**Comment by Flova** [comment]
I just got it compiling yesterday. The `mallet_tip` etc. are placehoders

**Review by cvhex — APPROVED** [review]

**Comment by Juphex** [comment]
Is this still a draft or can this be merged? @flova @cvhex

**Review by Juphex — APPROVED** [review]

**Comment by berkgungor** [comment]
@Juphex this PR is tested in visualization and ready

~Flova

**Pull request merged**
