### PR TITLE
Feature/GitHub Action build python requirements

### PR DESCRIPTION
**Pull request by Juphex**

### CODE REVIEW

**Comment by yunlong-wang-cn** [comment]
That sounds pretty useful, I am just curious how does this `main.yml` works? @Juphex

**Review by iibrahimli — APPROVED** [review]
LGTM

**Review by Flova — APPROVED** [review]
LGTM but this only checks if the installation is successful, things related to our python code are not changed.

**Comment by Juphex** [comment]
@Flova  you are right

**Comment by Juphex** [comment]
> That sounds pretty useful, I am just curious how does this `main.yml` works? @Juphex

It just runs ´pip install -r requirements.txt´ to make sure that it won't fail when installing the dependies.

**Pull request merged**
