### PR TITLE
Feature/extend hw notation

### PR DESCRIPTION
**Pull request by scaredycode**

### CODE REVIEW

**Comment by Juphex** [comment]
I tried it and had an error: Any idea why there is a difference between the generated pictures? (after first rest)
Also I get the output "unregocnized symbol" for r1, r2, r4, r8. But they seem occur in my generated picture below as well
image
image

**Comment by Juphex** [comment]
> > I tried it and had an error: Any idea why there is a difference between the generated pictures? (after first rest) Also I get the output "unregocnized symbol" for r1, r2, r4, r8. But they seem occur in my generated picture below as well
> 
> The rest issue should be fixed now, but I don't know why some notes dissappeared. do you have the lilypond script for this sample? I am still experimenting with the script but never had this issue in my samples.

Here you go if you need it

```
%! abjad.LilyPondFile._get_format_pieces()
\version "2.20.0"
%! abjad.LilyPondFile._get_format_pieces()
\language "english"

%! abjad.LilyPondFile._get_formatted_blocks()
\header
%! abjad.LilyPondFile._get_formatted_blocks()
{
    tagline = #ff
%! abjad.LilyPondFile._get_formatted_blocks()
}
#(set-default-paper-size "a8" 'landscape)
#(set-global-staff-size 16)
\context Staff = "Staff_1"
{
    \context Voice = "Voice_1"
    {
        b'8
        a'8
        b''8
        r8
        e'8
        g'8
        f'8
        c'8
        c''2
        f'8
        g'8
        a''4
        r8
        f'8
        g'4
        r2
    }
}
```

**Comment by Flova** [comment]
What is the state of this  @scaredycode and @Juphex ? Are we ready to generate a dataset and train with it?

**Review by Flova — APPROVED** [review]
Tbh I don't understand the code in detail xD , but if the results are good I would merge it.

**Review by Juphex — APPROVED** [review]

**Pull request merged**
