### PR TITLE
211 adjust the synthetic dataset generation

### PR DESCRIPTION
**Pull request by Juphex**
This PR fixes the dotted note problem (too many clocks in a bar)
simplifies the data that is generated by default
Adds a rotation to the output image, so this and the handwritten data are in portrait mode. (make generation a bit slower because it adds an extra read and write step)

### CODE REVIEW

**Comment by Juphex** [comment]
Dotted note examples:

grafik
grafik

**Comment by scaredycode** [comment]
The new beats-per-bar system works perfectly :)
However, some samples have 16th notes even though I set min_duration to 8. You might wan't to have a look at that. 
staff_1

**Comment by Juphex** [comment]
now the dotted note is not always followed by its duration/2

grafik

**Review by Flova — APPROVED** [review]

**Comment by Flova** [comment]
Lets also wait for the review of @scaredycode

**Review by scaredycode — CHANGES_REQUESTED** [review]
Please remove the double sharps & double flats. Also would be nice to randomize dynamics for every note (or every beginning bar) instead of just at the first position. Otherwise looks good.

**Pull request merged**
