### PR TITLE
HOWTO Readme for printing out 

### PR DESCRIPTION
**Pull request by ateRstones**
I started a HOWTO file to print and add to the box of parts.

Please extend as you see fit.

Especially the rqt part (as I don't know about it)

I copied most of the parts from other readmes

### CODE REVIEW

**Comment by yunlong-wang-cn** [comment]
We can also do/talk about this on Friday.

**Comment by Juphex** [comment]
Could you please add documentation on how to calibrate the position of the marimba? :)

**Comment by Flova** [comment]
And also how you can grab the mallet holder with rviz using the gripper

**Comment by ateRstones** [comment]
> And also how you can grab the mallet holder with rviz using the gripper

I added something about this in the hardware setup part. Do you think it should be changed?

**Comment by ateRstones** [comment]
> Could you please add documentation on how to calibrate the position of the marimba? :)

I added some steps for this, please check if they are correct

**Comment by yunlong-wang-cn** [comment]
I upload the section about how to setup the microphone and how to open visualization.

**Comment by Flova** [comment]
I fixed some spelling errors and reworked the overall structure, so it makes more sense for somebody who wants to get the system up and running. Especially some hardware that were explained separately in the end were required by software that was started in the beginning, so I interlaced it a little bit. Now, following the guide step by step should work. I also changed the calibration a bit.

**Review by yunlong-wang-cn — APPROVED** [review]
LGTM

**Review by Flova — APPROVED** [review]

**Pull request merged**
