### PR TITLE
Feature/repos file

### PR DESCRIPTION
**Pull request by berkgungor**
Imported workspace from TAMS UR5 machine.

### CODE REVIEW

**Comment by Flova** [comment]
Please consider adapting the GitHub actions, so that all repos are clones.

**Comment by Flova** [comment]
We could also move the bio_ik and audio_common submodules to this definition of everything works accordingly.

**Comment by Juphex** [comment]
Please resolve conflicts @iibrahimli

**Comment by Flova** [comment]
Now the CI passes, but still only builds some of the packages

**Comment by iibrahimli** [comment]
Yeah, I haven't figured out a (clean) way to copy contents of the parent directory (where vcstool clones stuff) to the industrial-ci

**Comment by Flova** [comment]
The industrial CI has a hook system for that. See its documentation: https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#run-prepost-process-custom-commands

**Comment by Flova** [comment]
You need to make the file executable

**Comment by Flova** [comment]
It seems like the CI is not able to find curl or git. It could be the case that they are not installed at this point or that the path / shell environment is not set and you would need the absolute path.

**Comment by Juphex** [comment]
please consider the changes of https://github.com/UHHRobotics22-23/robot_project/pull/46 

e.g. rebase

**Comment by Flova** [comment]
The CI is passing, yay

**Review by Flova — APPROVED** [review]

**Pull request merged**
