### PR TITLE
Use the lower notes for sharps

### PR DESCRIPTION
**Pull request by Flova**
PR #281 adds new hit points and this PR utilizes them in the motion.

### CODE REVIEW

**Comment by Flova** [comment]
This is totally untested as of now and waits for #283

**Comment by iibrahimli** [comment]
LG if either `ends_with` is implemented, or we switch to C++ 20 :D

**Review by Juphex — COMMENTED** [review]
perhaps you could use any function from https://stackoverflow.com/questions/874134/find-out-if-string-ends-with-another-string-in-c

**Comment by Flova** [comment]
Well the old CPP version strikes again...
We can use the boost ends_with tho. similar to the boost optional we are using.

**Comment by berkgungor** [comment]
I know it is a different PR, but I also pushed changes that enable the preemption / canceling of a running action.

**Review by yunlong-wang-cn — APPROVED** [review]
lgtm

**Pull request merged**
